services:
  myaw-nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - myaw-backend-main-service
      - myaw-frontend-client
      - myaw-frontend-admin

  myaw-db-mongo:
    image: mongo:7
    volumes:
      - myaw-db-mongo:/data/db

  myaw-backend-main-service:
    build:
      context: ./myaw-main-api
      dockerfile: ../docker/backend-main-api/Dockerfile
    depends_on:
      - myaw-db-mongo
    ports:
      - "3010:3000"
    
  myaw-backend-realtime-service:
    build:
      context: ./myaw-realtime-api
      dockerfile: ../docker/backend-realtime/Dockerfile
    depends_on:
      - myaw-db-mongo
    ports:
      - "3011:3000"

  myaw-frontend-client:
    build:
      context: ./myaw-frontend
      dockerfile: ../docker/frontend-client/Dockerfile.dev
    volumes:
      - ./myaw-frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - myaw-backend-main-service

  myaw-frontend-admin:
    build:
      context: ./myaw-frontend
      dockerfile: ../docker/frontend-admin/Dockerfile.dev
    volumes:
      - ./myaw-frontend:/app
      - /app/node_modules
    ports:
      - "4201:4201"
    depends_on:
      - myaw-backend-main-service

volumes:
  myaw-db-mongo: